#Struktur- und Dokumentinformationstags
from  element.data.i_tag import I 
from  element.data.canvas_tag import Canvas
from  element.data.caption_tag import Caption
from  element.data.dd_tag import Dd
from  element.data.dl_tag import Dl
from  element.data.li_tag import Li
from  element.data.ol_tag import Ol
from  element.data.q_tag import Q
from  element.data.table_tag import Table
from  element.data.tbody_tag import TBody
from  element.data.td_tag import Td
from  element.data.tfoot_tag import TFoot
from  element.data.th_tag import Th
from  element.data.thead_tag import Thead
from  element.data.time_tag import Time
from  element.data.tr_tag import Tr
from  element.data.tt_tag import Tt
from  element.fields.fieldset_tag  import Fieldset
from  element.fields.button_tag  import Button
from  element.fields.area_tag  import Area
from  element.fields.form_tag  import Form
from  element.fields.input_tag  import Input
from  element.fields.label  import Label
from  element.fields.legend_tag  import Legend
from  element.fields.option_tag  import Option
from  element.fields.select_tag  import Select
from  element.fields.textarea_tag  import TextArea
from  element.layout.abbr_tag  import Abbr
from  element.layout.acronym_tag  import Acronym
from  element.layout.address_tag  import Address
from  element.layout.applet_tag  import Applet
from  element.layout.article_tag  import Article
from  element.layout.aside_tag  import Aside
from  element.layout.base_tag  import Base
from  element.layout.basefont_tag  import BaseFont
from  element.layout.bdi_tag  import Bdi
from  element.layout.bdo_tag  import Bdo
from  element.layout.big_tag  import Big
from  element.layout.body_tag  import Body
from  element.layout.bold_tag  import Bold
from  element.layout.centerelement_tag  import CenterElement
from  element.layout.cite_tag  import Cite
from  element.layout.code_tag  import Code
from  element.layout.col_tag  import Col
from  element.layout.colgroup_tag  import Colgroup
from  element.layout.data_tag  import Data
from  element.layout.datalist_tag  import DataList
from  element.layout.del_tag  import Del
from  element.layout.details_tyg  import Details
from  element.layout.dfn_tag  import Dfn
from  element.layout.dialog_tag import Dialog
from  element.layout.dir_tag  import Dir
from  element.layout.div_tag  import Div
from  element.layout.nav_tag  import Nav
from  element.layout.noframes_tag  import NoFrames
from  element.layout.noscript_tag  import NoScript
from  element.layout.object_tag  import Object
from  element.layout.optgroup_tag  import Optgroup
from  element.layout.output_tag  import Output
from  element.layout.rp_tag  import Rp
from  element.layout.rt_tag  import Rt
from  element.layout.ruby_tag  import Ruby
from  element.layout.samp_tag  import Samp
from  element.layout.script_tag  import Script
from  element.layout.section_tag  import Section
from  element.layout.strike_tag  import Strike
from  element.layout.span_tag  import Span
from  element.layout.style_tag  import Style
from  element.layout.summary_tag  import Summary
from  element.layout.svg_tag  import SVG
from  element.layout.template_tag  import Template
from  element.layout.title_tag  import Title
from  element.layout.track_tag  import Track
from  element.layout.var_tag import Var
from  element.layout.wbr_tag  import Wbr
from  element.layout.main_tag  import Main
from  element.layout.map_tag  import Map
from  element.layout.meter_tag  import Meter
from  element.layout.link_tag  import Link
from  element.layout.kbd_tag  import Kbd
from  element.layout.iframe_tag  import Iframe
from  element.layout.ins_tag  import Ins
from  element.layout.head_tag  import Head
from  element.layout.header_tag  import Header
from  element.layout.html_tag  import Html
from  element.layout.figcaption_tag  import Figcaption
from  element.layout.figure_tag  import Figuer
from  element.layout.font_tag  import Font
from  element.layout.frame_tag  import Frame
from  element.layout.frameset_tag  import Frameset
from  element.medientag.a_tag import A
from  element.medientag.img_tag import Img
from  element.medientag.video_tag import Video
from  element.typography.blockquote_tag import Blockquote
from  element.typography.br_tag import Br
from  element.typography.em_tag import Em
from  element.typography.h_tag import H1
from  element.typography.h_tag import H2
from  element.typography.h_tag import H3
from  element.typography.h_tag import H4
from  element.typography.h_tag import H5
from  element.typography.h_tag import H6
from  element.typography.hr_tag import Hr
from  element.typography.mark_tag import Mark
from  element.typography.p_tag import P
from  element.typography.pre_tag import Pre
from  element.typography.s_tag import S
from  element.typography.strong_tag import Strong
from  element.typography.sub_tag import Sub
from  element.typography.sup_tag import Sup
from  element.typography.u_tag import U
from element.styles.inline_style import Style
from app import App