import json

class Style:
    def __init__(
        self,
        align_content: str = None,
        align_items: str = None,
        align_self: str = None,
        all: str = None,
        animation: str = None,
        animation_delay: str = None,
        animation_direction: str = None,
        animation_duration: str = None,
        animation_fill_mode: str = None,
        animation_iteration_count: str = None,
        animation_name: str =None ,
        animation_play_state: str = None,
        animation_timing_function: str = None,
        backface_visibility: str = None,
        background: str = None,
        background_attachment: str = None,
        background_blend_mode: str = None,
        background_clip: str = None,
        background_color: str = None,
        background_image: str = None,
        background_origin: str = None,
        background_position: str = None,
        background_repeat: str = None,
        background_size: str = None,
        block_size: str = None,
        border: str = None,
        border_block: str = None,
        border_block_color: str = None,
        border_block_end: str = None,
        border_block_end_color: str = None,
        border_block_end_style: str = None,
        border_block_end_width: str = None,
        border_block_start: str = None,
        border_block_start_color: str = None,
        border_block_start_style: str = None,
        border_block_start_width: str = None,
        border_block_style: str = None,
        border_block_width: str = None,
        border_bottom: str = None,
        border_bottom_color: str = None,
        border_bottom_left_radius: str = None,
        border_bottom_right_radius: str = None,
        border_bottom_style: str = None,
        border_bottom_width: str = None,
        border_collapse: str = None,
        border_color: str = None,
        border_end_end_radius: str = None,
        border_end_start_radius: str = None,
        border_image: str = None,
        border_image_outset: str = None,
        border_image_repeat: str = None,
        border_image_slice: str = None,
        border_image_source: str = None,
        border_image_width: str = None,
        border_inline: str = None,
        border_inline_color: str = None,
        border_inline_end: str = None,
        border_inline_end_color: str = None,
        border_inline_end_style: str = None,
        border_inline_end_width: str = None,
        border_inline_start: str = None,
        border_inline_start_color: str = None,
        border_inline_start_style: str = None,
        border_inline_start_width: str = None,
        border_inline_style: str = None,
        border_inline_width: str = None,
        border_left: str = None,
        border_left_color: str = None,
        border_left_style: str = None,
        border_left_width: str = None,
        border_radius: str = None,
        border_right: str = None,
        border_right_color: str = None,
        border_right_style: str = None,
        border_right_width: str = None,
        border_spacing: str = None,
        border_start_end_radius: str = None,
        border_start_start_radius: str = None,
        border_style: str = None,
        border_top: str = None,
        border_top_color: str = None,
        border_top_left_radius: str = None,
        border_top_right_radius: str = None,
        border_top_style: str = None,
        border_top_width: str = None,
        border_width: str = None,
        bottom: str = None,
        box_decoration_break: str = None,
        box_shadow: str = None,
        box_sizing: str = None,
        break_after: str = None,
        break_before: str = None,
        break_inside: str = None,
        caption_side: str = None,
        caret_color: str = None,
        clear: str = None,
        clip: str = None,
        color: str = None,
        column_count: str = None,
        column_fill: str = None,
        column_gap: str = None,
        column_rule: str = None,
        column_rule_color: str = None,
        column_rule_style: str = None,
        column_rule_width: str = None,
        column_span: str = None,
        column_width: str = None,
        columns: str = None,
        content: str = None,
        counter_increment: str = None,
        counter_reset: str = None,
        cursor: str = None,
        direction: str = None,
        display: str = None,
        empty_cells: str = None,
        filter: str = None,
        flex: str = None,
        flex_basis: str = None,
        flex_direction: str = None,
        flex_flow: str = None,
        flex_grow: str = None,
        flex_shrink: str = None,
        flex_wrap: str = None,
        float: str = None,
        font: str = None,
        font_family: str = None,
        font_feature_settings: str = None,
        font_kerning: str = None,
        font_language_override: str = None,
        font_optical_sizing: str = None,
        font_size: str = None,
        font_size_adjust: str = None,
        font_stretch: str = None,
        font_style: str = None,
        font_synthesis: str = None,
        font_variant: str = None,
        font_variant_alternates: str = None,
        font_variant_caps: str = None,
        font_variant_east_asian: str = None,
        font_variant_ligatures: str = None,
        font_variant_numeric: str = None,
        font_variant_position: str = None,
        font_weight: str = None,
        gap: str = None,
        grid: str = None,
        grid_area: str = None,
        grid_auto_columns: str = None,
        grid_auto_flow: str = None,
        grid_auto_rows: str = None,
        grid_column: str = None,
        grid_column_end: str = None,
        grid_column_start: str = None,
        grid_row: str = None,
        grid_row_end: str = None,
        grid_row_start: str = None,
        grid_template: str = None,
        grid_template_areas: str = None,
        grid_template_columns: str = None,
        grid_template_rows: str = None,
        hanging_punctuation: str = None,
        height: str = None,
        hyphens: str = None,
        image_orientation: str = None,
        image_rendering: str = None,
        image_resolution: str = None,
        ime_mode: str = None,
        initial_letter: str = None,
        initial_letter_align: str = None,
        inline_size: str = None,
        inset: str = None,
        inset_block: str = None,
        inset_block_end: str = None,
        inset_block_start: str = None,
        inset_inline: str = None,
        inset_inline_end: str = None,
        inset_inline_start: str = None,
        isolation: str = None,
        justify_content: str = None,
        justify_items: str = None,
        justify_self: str = None,
        left: str = None,
        letter_spacing: str = None,
        line_break: str = None,
        line_height: str = None,
        list_style: str = None,
        list_style_image: str = None,
        list_style_position: str = None,
        list_style_type: str = None,
        margin: str = None,
        margin_block: str = None,
        margin_block_end: str = None,
        margin_block_start: str = None,
        margin_bottom: str = None,
        margin_inline: str = None,
        margin_inline_end: str = None,
        margin_inline_start: str = None,
        margin_left: str = None,
        margin_right: str = None,
        margin_top: str = None,
        mask: str = None,
        mask_clip: str = None,
        mask_composite: str = None,
        mask_image: str = None,
        mask_mode: str = None,
        mask_origin: str = None,
        mask_position: str = None,
        mask_repeat: str = None,
        mask_size: str = None,
        mask_type: str = None,
        max_block_size: str = None,
        max_height: str = None,
        max_inline_size: str = None,
        max_width: str = None,
        min_block_size: str = None,
        min_height: str = None,
        min_inline_size: str = None,
        min_width: str = None,
        mix_blend_mode: str = None,
        object_fit: str = None,
        object_position: str = None,
        offset: str = None,
        offset_anchor: str = None,
        offset_block: str = None,
        offset_block_end: str = None,
        offset_block_start: str = None,
        offset_distance: str = None,
        offset_inline: str = None,
        offset_inline_end: str = None,
        offset_inline_start: str = None,
        offset_path: str = None,
        offset_position: str = None,
        offset_rotate: str = None,
        opacity: str = None,
        order: str = None,
        orphans: str = None,
        outline: str = None,
        outline_color: str = None,
        outline_offset: str = None,
        outline_style: str = None,
        outline_width: str = None,
        overflow: str = None,
        overflow_anchor: str = None,
        overflow_block: str = None,
        overflow_inline: str = None,
        overflow_wrap: str = None,
        overflow_x: str = None,
        overflow_y: str = None,
        overscroll_behavior: str = None,
        overscroll_behavior_block: str = None,
        overscroll_behavior_inline: str = None,
        overscroll_behavior_x: str = None,
        overscroll_behavior_y: str = None,
        padding: str = None,
        padding_block: str = None,
        padding_block_end: str = None,
        padding_block_start: str = None,
        padding_bottom: str = None,
        padding_inline: str = None,
        padding_inline_end: str = None,
        padding_inline_start: str = None,
        padding_left: str = None,
        padding_right: str = None,
        padding_top: str = None,
        page_break_after: str = None,
        page_break_before: str = None,
        page_break_inside: str = None,
        paint_order: str = None,
        perspective: str = None,
        perspective_origin: str = None,
        place_content: str = None,
        place_items: str = None,
        place_self: str = None,
        pointer_events: str = None,
        position: str = None,
        quotes: str = None,
        resize: str = None,
        right: str = None,
        rotate: str = None,
        row_gap: str = None,
        ruby_align: str = None,
        ruby_merge: str = None,
        ruby_position: str = None,
        scale: str = None,
        scroll_behavior: str = None,
        scroll_margin: str = None,
        scroll_margin_block: str = None,
        scroll_margin_block_end: str = None,
        scroll_margin_block_start: str = None,
        scroll_margin_bottom: str = None,
        scroll_margin_inline: str = None,
        scroll_margin_inline_end: str = None,
        scroll_margin_inline_start: str = None,
        scroll_margin_left: str = None,
        scroll_margin_right: str = None,
        scroll_margin_top: str = None,
        scroll_padding: str = None,
        scroll_padding_block: str = None,
        scroll_padding_block_end: str = None,
        scroll_padding_block_start: str = None,
        scroll_padding_bottom: str = None,
        scroll_padding_inline: str = None,
        scroll_padding_inline_end: str = None,
        scroll_padding_inline_start: str = None,
        scroll_padding_left: str = None,
        scroll_padding_right: str = None,
        scroll_padding_top: str = None,
        scroll_snap_align: str = None,
        scroll_snap_stop: str = None,
        scroll_snap_type: str = None,
        shape_image_threshold: str = None,
        shape_margin: str = None,
        shape_outside: str = None,
        tab_size: str = None,
        table_layout: str = None,
        text_align: str = None,
        text_align_last: str = None,
        text_combine_upright: str = None,
        text_decoration: str = None,
        text_decoration_color: str = None,
        text_decoration_line: str = None,
        text_decoration_skip_ink: str = None,
        text_decoration_style: str = None,
        text_decoration_thickness: str = None,
        text_emphasis: str = None,
        text_emphasis_color: str = None,
        text_emphasis_position: str = None,
        text_emphasis_style: str = None,
        text_indent: str = None,
        text_justify: str = None,
        text_orientation: str = None,
        text_overflow: str = None,
        text_rendering: str = None,
        text_shadow: str = None,
        text_size_adjust: str = None,
        text_transform: str = None,
        text_underline_offset: str = None,
        text_underline_position: str = None,
        top: str = None,
        touch_action: str = None,
        transform: str = None,
        transform_box: str = None,
        transform_origin: str = None,
        transform_style: str = None,
        transition: str = None,
        transition_delay: str = None,
        transition_duration: str = None,
        transition_property: str = None,
        transition_timing_function: str = None,
        unicode_bidi: str = None,
        user_select: str = None,
        vertical_align: str = None,
        visibility: str = None,
        white_space: str = None,
        widows: str = None,
        width: str = None,
        will_change: str = None,
        word_break: str = None,
        word_spacing: str = None,
        writing_mode: str = None,
        z_index: str = None,
        ):
        self.align_content = align_content,
        self.align_items = align_items,
        self.align_self = align_self,
        self.all = all,
        self.animation = animation,
        self.animation_delay = animation_delay,
        self.animation_direction = animation_direction,
        self.animation_duration = animation_duration,
        self.animation_fill_mode = animation_fill_mode,
        self.animation_iteration_count = animation_iteration_count,
        self.animation_name = animation_name,
        self.animation_play_state = animation_play_state,
        self.animation_timing_function = animation_timing_function,
        self.backface_visibility = backface_visibility,
        self.background = background,
        self.background_attachment = background_attachment,
        self.background_blend_mode = background_blend_mode,
        self.background_clip = background_clip,
        self.background_color = background_color,
        self.background_image = background_image,
        self.background_origin = background_origin,
        self.background_position = background_position,
        self.background_repeat =background_repeat ,
        self.background_size = background_size,
        self.block_size = block_size,
        self.border = border,
        self.border_block = border_block,
        self.border_block_color = border_block_color,
        self.border_block_end = border_block_end,
        self.border_block_end_color = border_block_end_color,
        self.border_block_end_style = border_block_end_style,
        self.border_block_end_width = border_block_end_width,
        self.border_block_start = border_block_start,
        self.border_block_start_color = border_block_start_color,
        self.border_block_start_style = border_block_start_style,
        self.border_block_start_width = border_block_start_width,
        self.border_block_style = border_block_style,
        self.border_block_width = border_block_width,
        self.border_bottom = border_bottom,
        self.border_bottom_color =border_bottom_color ,
        self.border_bottom_left_radius = border_bottom_left_radius,
        self.border_bottom_right_radius = border_bottom_right_radius,
        self.border_bottom_style = border_bottom_style,
        self.border_bottom_width = border_bottom_width,
        self.border_collapse = border_collapse,
        self.border_color = border_color,
        self.border_end_end_radius = border_end_end_radius,
        self.border_end_start_radius = border_end_start_radius,
        self.border_image = border_image,
        self.border_image_outset = border_image_outset ,
        self.border_image_repeat = border_image_repeat,
        self.border_image_slice = border_image_slice,
        self.border_image_source = border_image_source,
        self.border_image_width = border_image_width,
        self.border_inline = border_inline,
        self.border_inline_color = border_inline_color,
        self.border_inline_end = border_inline_end,
        self.border_inline_end_color = border_inline_end_color,
        self.border_inline_end_style = border_inline_end_style,
        self.border_inline_end_width = border_inline_end_width,
        self.border_inline_start = border_inline_start,
        self.border_inline_start_color = border_inline_start_color,
        self.border_inline_start_style = border_inline_start_style,
        self.border_inline_start_width = border_inline_start_width,
        self.border_inline_style = border_inline_style,
        self.border_inline_width = border_inline_width,
        self.border_left = border_left,
        self.border_left_color = border_left_color,
        self.border_left_style = border_left_style,
        self.border_left_width = border_left_width,
        self.border_radius = border_radius,
        self.border_right = border_right,
        self.border_right_color = border_right_color,
        self.border_right_style = border_right_style,
        self.border_right_width = border_right_width,
        self.border_spacing = border_spacing,
        self.border_start_end_radius =border_start_end_radius ,
        self.border_start_start_radius = border_start_start_radius,
        self.border_style = border_style,
        self.border_top = border_top,
        self.border_top_color = border_top_color,
        self.border_top_left_radius = border_top_left_radius,
        self.border_top_right_radius = border_top_right_radius,
        self.border_top_style = border_top_style,
        self.border_top_width = border_top_width,
        self.border_width = border_width,
        self.bottom = bottom,
        self.box_decoration_break = box_decoration_break,
        self.box_shadow = box_shadow,
        self.box_sizing = box_sizing,
        self.break_after =break_after ,
        self.break_before = break_before,
        self.break_inside = break_inside,
        self.caption_side = caption_side,
        self.caret_color = caret_color,
        self.clear = clear ,
        self.clip = clip,
        self.color = color,
        self.column_count = column_count,
        self.column_fill = column_fill,
        self.column_gap = column_gap,
        self.column_rule = column_rule,
        self.column_rule_color = column_rule_color,
        self.column_rule_style = column_rule_style,
        self.column_rule_width = column_rule_width,
        self.column_span = column_span,
        self.column_width = column_width,
        self.columns = columns,
        self.content = content,
        self.counter_increment = counter_increment ,
        self.counter_reset = counter_reset,
        self.cursor = cursor,
        self.direction = direction,
        self.display = display,
        self.empty_cells = empty_cells,
        self.filter = filter,
        self.flex = flex,
        self.flex_basis = flex_basis,
        self.flex_direction = flex_direction,
        self.flex_flow = flex_flow,
        self.flex_grow = flex_grow,
        self.flex_shrink = flex_shrink,
        self.flex_wrap = flex_wrap,
        self.float = float,
        self.font = font,
        self.font_family = font_family,
        self.font_feature_settings = font_feature_settings,
        self.font_kerning = font_kerning,
        self.font_language_override = font_language_override,
        self.font_optical_sizing = font_optical_sizing,
        self.font_size = font_size,
        self.font_size_adjust = font_size_adjust,
        self.font_stretch =font_stretch ,
        self.font_style =font_style ,
        self.font_synthesis = font_synthesis,
        self.font_variant = font_variant,
        self.font_variant_alternates =font_variant_alternates,
        self.font_variant_caps = font_variant_caps,
        self.font_variant_east_asian = font_variant_east_asian,
        self.font_variant_ligatures = font_variant_ligatures,
        self.font_variant_numeric = font_variant_numeric,
        self.font_variant_position = font_variant_position,
        self.font_weight = font_weight,
        self.gap = gap,
        self.grid = grid,
        self.grid_area = grid_area,
        self.grid_auto_columns = grid_auto_columns,
        self.grid_auto_flow = grid_auto_flow,
        self.grid_auto_rows = grid_auto_rows,
        self.grid_column = grid_column,
        self.grid_column_end = grid_column_end,
        self.grid_column_start = grid_column_start,
        self.grid_row = grid_row,
        self.grid_row_end = grid_row_end,
        self.grid_row_start = grid_row_start,
        self.grid_template = grid_template,
        self.grid_template_areas = grid_template_areas,
        self.grid_template_columns = grid_template_columns,
        self.grid_template_rows = grid_template_rows,
        self.hanging_punctuation = hanging_punctuation,
        self.height = height,
        self.hyphens = hyphens,
        self.image_orientation = image_orientation,
        self.image_rendering = image_rendering,
        self.image_resolution = image_resolution,
        self.ime_mode = ime_mode,
        self.initial_letter = initial_letter,
        self.initial_letter_align = initial_letter_align,
        self.inline_size = inline_size,
        self.inset = inset,
        self.inset_block = inset_block,
        self.inset_block_end = inset_block_end,
        self.inset_block_start = inset_block_start,
        self.inset_inline = inset_inline,
        self.inset_inline_end = inset_inline_end,
        self.inset_inline_start = inset_inline_start,
        self.isolation = isolation,
        self.justify_content = justify_content,
        self.justify_items = justify_items,
        self.justify_self = justify_self,
        self.left = left,
        self.letter_spacing = letter_spacing,
        self.line_break = line_break,
        self.line_height = line_height,
        self.list_style = list_style,
        self.list_style_image = list_style_image,
        self.list_style_position = list_style_position,
        self.list_style_type = list_style_type,
        self.margin = margin,
        self.margin_block = margin_block,
        self.margin_block_end = margin_block_end,
        self.margin_block_start = margin_block_start,
        self.margin_bottom = margin_bottom,
        self.margin_inline = margin_inline,
        self.margin_inline_end = margin_inline_end,
        self.margin_inline_start = margin_inline_start,
        self.margin_left = margin_left,
        self.margin_right = margin_right,
        self.margin_top = margin_top,
        self.mask = mask,
        self.mask_clip = mask_clip,
        self.mask_composite =mask_composite,
        self.mask_image = mask_image,
        self.mask_mode = mask_mode,
        self.mask_origin = mask_origin,
        self.mask_position = mask_position,
        self.mask_repeat = mask_repeat,
        self.mask_size = mask_size,
        self.mask_type = mask_type,
        self.max_block_size = max_block_size,
        self.max_height = max_height,
        self.max_inline_size =max_inline_size ,
        self.max_width = max_width,
        self.min_block_size = min_block_size,
        self.min_height = min_height,
        self.min_inline_size = min_inline_size,
        self.min_width = min_width,
        self.mix_blend_mode = mix_blend_mode,
        self.object_fit = object_fit,
        self.object_position = object_position,
        self.offset = offset,
        self.offset_anchor = offset_anchor,
        self.offset_block = offset_block,
        self.offset_block_end = offset_block_end,
        self.offset_block_start = offset_block_start,
        self.offset_distance = offset_distance,
        self.offset_inline = offset_inline,
        self.offset_inline_end = offset_inline_end,
        self.offset_inline_start = offset_inline_start,
        self.offset_path = offset_path,
        self.offset_position = offset_position,
        self.offset_rotate = offset_rotate,
        self.opacity = opacity,
        self.order = order ,
        self.orphans = orphans,
        self.outline = outline,
        self.outline_color = outline_color,
        self.outline_offset = outline_offset,
        self.outline_style = outline_style,
        self.outline_width = outline_width,
        self.overflow = overflow,
        self.overflow_anchor = overflow_anchor,
        self.overflow_block = overflow_block,
        self.overflow_inline = overflow_inline,
        self.overflow_wrap = overflow_wrap,
        self.overflow_x = overflow_x,
        self.overflow_y = overflow_y,
        self.overscroll_behavior = overscroll_behavior,
        self.overscroll_behavior_block = overscroll_behavior_block,
        self.overscroll_behavior_inline = overscroll_behavior_inline,
        self.overscroll_behavior_x = overscroll_behavior_x,
        self.overscroll_behavior_y = overscroll_behavior_y,
        self.padding = padding,
        self.padding_block = padding_block,
        self.padding_block_end = padding_block_end,
        self.padding_block_start = padding_block_start,
        self.padding_bottom = padding_bottom,
        self.padding_inline = padding_inline,
        self.padding_inline_end = padding_inline_end,
        self.padding_inline_start = padding_inline_start,
        self.padding_left = padding_left,
        self.padding_right = padding_right,
        self.padding_top = padding_top,
        self.page_break_after = page_break_after,
        self.page_break_before = page_break_before,
        self.page_break_inside = page_break_inside,
        self.paint_order = paint_order,
        self.perspective = perspective,
        self.perspective_origin = perspective_origin,
        self.place_content = place_content,
        self.place_items = place_items,
        self.place_self = place_self,
        self.pointer_events = pointer_events,
        self.position = position,
        self.quotes = quotes,
        self.resize = resize,
        self.right = right,
        self.rotate = rotate,
        self.row_gap =row_gap,
        self.ruby_align = ruby_align,
        self.ruby_merge =ruby_merge ,
        self.ruby_position = ruby_position,
        self.scale = scale,
        self.scroll_behavior = scroll_behavior,
        self.scroll_margin = scroll_margin,
        self.scroll_margin_block = scroll_margin_block,
        self.scroll_margin_block_end = scroll_margin_block_end,
        self.scroll_margin_block_start = scroll_margin_block_start,
        self.scroll_margin_bottom =scroll_margin_bottom ,
        self.scroll_margin_inline = scroll_margin_inline,
        self.scroll_margin_inline_end = scroll_margin_inline_end,
        self.scroll_margin_inline_start =scroll_margin_inline_start ,
        self.scroll_margin_left = scroll_margin_left,
        self.scroll_margin_right =scroll_margin_right ,
        self.scroll_margin_top = scroll_margin_top,
        self.scroll_padding = scroll_padding,
        self.scroll_padding_block = scroll_padding_block,
        self.scroll_padding_block_end = scroll_padding_block_end,
        self.scroll_padding_block_start = scroll_padding_block_start,
        self.scroll_padding_bottom = scroll_padding_bottom,
        self.scroll_padding_inline = scroll_padding_inline,
        self.scroll_padding_inline_end =scroll_padding_inline_end ,
        self.scroll_padding_inline_start = scroll_padding_inline_start,
        self.scroll_padding_left = scroll_padding_left,
        self.scroll_padding_right = scroll_padding_right,
        self.scroll_padding_top = scroll_padding_top,
        self.scroll_snap_align = scroll_snap_align,
        self.scroll_snap_stop = scroll_snap_stop,
        self.scroll_snap_type = scroll_snap_type,
        self.shape_image_threshold = shape_image_threshold,
        self.shape_margin = shape_margin,
        self.shape_outside = shape_outside,
        self.tab_size = tab_size,
        self.table_layout = table_layout,
        self.text_align = text_align,
        self.text_align_last = text_align_last,
        self.text_combine_upright =text_combine_upright ,
        self.text_decoration = text_decoration,
        self.text_decoration_color = text_decoration_color,
        self.text_decoration_line = text_decoration_line,
        self.text_decoration_skip_ink = text_decoration_skip_ink,
        self.text_decoration_style = text_decoration_style,
        self.text_decoration_thickness = text_decoration_thickness,
        self.text_emphasis = text_emphasis,
        self.text_emphasis_color = text_emphasis_color,
        self.text_emphasis_position = text_emphasis_position,
        self.text_emphasis_style = text_emphasis_style,
        self.text_indent = text_indent,
        self.text_justify = text_justify,
        self.text_orientation = text_orientation,
        self.text_overflow = text_overflow ,
        self.text_rendering = text_rendering,
        self.text_shadow = text_shadow,
        self.text_size_adjust = text_size_adjust,
        self.text_transform = text_transform,
        self.text_underline_offset = text_underline_offset,
        self.text_underline_position = text_underline_position,
        self.top =top ,
        self.touch_action = touch_action,
        self.transform = transform,
        self.transform_box = transform_box,
        self.transform_origin = transform_origin,
        self.transform_style =transform_style ,
        self.transition =transition ,
        self.transition_delay = transition_delay,
        self.transition_duration = transition_duration,
        self.transition_property = transition_property,
        self.transition_timing_function = transition_timing_function,
        self.unicode_bidi = unicode_bidi,
        self.user_select = user_select,
        self.vertical_align = vertical_align,
        self.visibility = visibility,
        self.white_space = white_space,
        self.widows = widows,
        self.width = width,
        self.will_change = will_change,
        self.word_break = word_break,
        self.word_spacing = word_spacing,
        self.writing_mode = writing_mode,
        self.z_index = z_index,



        
    def json_(self)-> dict:
        pyload = styles = {
            "align-content": self.align_content,
            "align-items": self.align_items,
            "align-self": self.align_self,
            "all": self.all,
            "animation": self.animation,
            "animation-delay": self.animation_delay,
            "animation-direction": self.animation_direction,
            "animation-duration": self.animation_duration,
            "animation-fill-mode": self.animation_fill_mode,
            "animation-iteration-count": self.animation_iteration_count,
            "animation-name": self.animation_name,
            "animation-play-state": self.animation_play_state,
            "animation-timing-function": self.animation_timing_function,
            "backface-visibility": self.backface_visibility,
            "background": self.background,
            "background-attachment": self.background_attachment,
            "background-blend-mode": self.background_blend_mode,
            "background-clip": self.background_clip,
            "background-image": self.background_image,
            "background-origin": self.background_origin,
            "background-position": self.background_position,
            "background-repeat": self.background_repeat,
            "background-size": self.background_size,
            "block-size": self.block_size,
            "border-block": self.border_block,
            "border-block-color": self.border_block_color,
            "border-block-end": self.border_block_end,
            "border-block-end-color": self.border_block_end_color, 
            "border-block-end-style": self.border_block_end_style,
            "border-block-end-width": self.border_block_end_width,
            "border-block-start": self.border_block_start,
            "border-block-start-color": self.border_block_start_color,
            "border-block-start-style": self.border_block_start_style,
            "border-block-start-width": self.border_block_start_width,
            "border-block-style": self.border_block_style,
            "border-block-width": self.border_block_width,
            "border-bottom": self.border_bottom,
            "border-bottom-color": self.border_bottom_color,
            "border-bottom-left_radius": self.border_bottom_left_radius ,
            "border-bottom-right_radius": self.border_bottom_right_radius,
            "border-bottom-style": self.border_bottom_style,
            "border-bottom-width": self.border_bottom_width,
            "border-collapse": self.border_collapse,
            "border-color": self.border_color,
            "border-end-end-radius": self.border_end_end_radius,
            "border-end-start-radius": self.border_end_start_radius,
            "border-image":self.border_image,
            "border-image-outset": self.border_image_outset,
            "border-image-repeat": self.border_image_repeat,
            "border-image-slice": self.border_image_slice,
            "border-image-source": self.border_image_source,
            "border-image-width": self.border_image_width,
            "border-inline": self.border_inline,
            "border-inline-color": self.border_inline_color,
            "border-inline-end": self.border_inline_end,
            "border-inline-end-color": self.border_inline_end_color,
            "border-inline-end-style": self.border_inline_end_style,
            "border-inline-end-width": self.border_inline_end_width,
            "border-inline-start": self.border_inline_start,
            "border-inline-start-color": self.border_inline_start_color,
            "border-inline-start-style": self.border_inline_start_style,
            "border-inline-start-width": self.border_inline_start_width,
            "border-inline-style": self.border_inline_style,
            "border-inline-width": self.border_inline_width,
            "border-left": self.border_left,
            "border-left-color": self.border_left_color,
            "border-left-style": self.border_left_style,
            "border-left-width": self.border_left_width,
            "border-radius": self.border_radius,
            "border-right": self.border_right,
            "border-right-color": self.border_right_color,
            "border-right-style": self.border_right_style,
            "border-right-width": self.border_right_width,
            "border-spacing": self.border_spacing,
            "border-start-end-radius": self.border_start_end_radius,
            "border-start-start-radius": self.border_start_start_radius,
            "border-style": self.border_style,
            "border-top": self.border_top,
            "background-color": self.background_color,
            "border": self.border,
            "bottom": self.bottom,
            "border-top-color": self.border_top_color,
            "border-top-left-radius": self.border_top_left_radius,
            "border-top-right-radius": self.border_top_right_radius,
            "border-top-style": self.border_top_style,
            "border-top-width": self.border_top_width,
            "border-width": self.border_width,
            "box-decoration-break": self.box_decoration_break,
            "box-shadow": self.box_shadow ,
            "box-sizing": self.box_sizing,
            "break-after": self.break_after,
            "break-before": self.break_before,
            "break-inside": self.break_inside,
            "caption-side": self.caption_side,
            "caret-color": self.caret_color,
            "clear": self.clear,
            "clip": self.clip,
            "color": self.color,
            "column-count": self.column_count,
            "column-fill": self.column_fill,
            "column-gap": self.column_gap,
            "column-rule": self.column_rule,
            "column-rule-color": self.column_rule_color,
            "column-rule-style": self.column_rule_style,
            "column-rule-width": self.column_rule_width ,
            "column-span": self.column_span,
            "column-width": self.column_width,
            "columns": self.columns,
            "content": self.content,
            "counter-increment": self.counter_increment,
            "counter-reset": self.counter_reset ,
            "cursor": self.cursor,
            "direction": self.direction,
            "display": self.display,
            "empty-cells": self.empty_cells,
            "filter":self.filter ,
            "flex": self.flex,
            "flex-basis": self.flex_basis,
            "flex-direction": self.flex_direction,
            "flex-flow": self.flex_flow,
            "flex-grow": self.flex_grow,
            "flex-shrink": self.flex_shrink,
            "flex-wrap": self.flex_wrap,
            "float": self.float,
            "font": self.font,
            "font-family": self.font_family,
            "font-feature-settings": self.font_feature_settings,
            "font-kerning": self.font_kerning,
            "font-language-override": self.font_language_override,
            "font-optical-sizing": self.font_optical_sizing,
            "font-size-adjust": self.font_size_adjust,
            "font-stretch": self.font_stretch,
            "font-synthesis": self.font_synthesis,
            "font-variant": self.font_variant,
            "font-variant-alternates": self.font_variant_alternates,
            "font-variant-caps": self.font_variant_caps,
            "font-variant-east_asian": self.font_variant_east_asian,
            "font-variant-ligatures": self.font_variant_ligatures,
            "font-variant-numeric": self.font_variant_numeric,
            "font-variant-position": self.font_variant_position,
            "font-size": self.font_size,
            "font-style": self.font_style,
            "font-weight": self.font_weight ,
            "gap": self.gap,
            "grid": self.grid,
            "grid-area": self.grid_area,
            "grid-auto-columns": self.grid_auto_columns,
            "grid-auto-flow": self.grid_auto_flow,
            "grid-auto-rows": self.grid_auto_rows,
            "grid-column": self.grid_column,
            "grid-column-end": self.grid_column_end,
            "grid-column-start": self.grid_column_start,
            "grid-row": self.grid_row,
            "grid-row-end": self.grid_row_end,
            "grid-row-start": self.grid_row_start,
            "grid-template": self.grid_template,
            "grid-template-areas": self.grid_template_areas,
            "grid-template-columns": self.grid_template_columns,
            "grid-template-rows": self.grid_template_rows,
            "hanging-punctuation": self.hanging_punctuation,
            "height": self.height,
            "hyphens": self.hyphens,
            "image-orientation": self.image_orientation,
            "image-rendering": self.image_rendering,
            "image-resolution": self.image_resolution,
            "ime-mode": self.ime_mode,
            "initial-letter": self.initial_letter,
            "initial-letter-align": self.initial_letter_align,
            "inline-size": self.inline_size,
            "inset": self.inset,
            "inset-block": self.inset_block,
            "inset-block-end": self.inset_block_end,
            "inset-block-start": self.inset_block_start,
            "inset-inline": self.inset_inline,
            "inset-inline-end": self.inset_inline_end,
            "inset-inline-start": self.inset_inline_start ,
            "isolation": self.isolation ,
            "justify-content": self.justify_content,
            "justify-items": self.justify_items,
            "justify-self": self.justify_self,
            "letter-spacing": self.letter_spacing,
            "line-break": self.line_break,
            "line-height": self.line_height,
            "list-style": self.list_style,
            "list-style-image": self.list_style_image,
            "list-style-position": self.list_style_position,
            "list-style-type": self.list_style_type,
            "left": self.left,
            "margin":self.margin ,
            "margin-block": self.margin_block,
            "margin-block-end": self.margin_block_end,
            "margin-block-start": self.margin_block_start,
            "margin-bottom": self.margin_bottom,
            "margin-inline": self.margin_inline,
            "margin-inline-end": self.margin_inline_end ,
            "margin-inline-start": self.margin_inline_start ,
            "margin-left": self.margin_left,
            "margin-right": self.margin_right,
            "margin-top": self.margin_top,
            "mask": self.mask,
            "mask-clip": self.mask_clip,
            "mask-composite": self.mask_composite,
            "mask-image": self.mask_image,
            "mask-mode": self.mask_mode,
            "mask-origin": self.mask_origin,
            "mask-position": self.mask_position ,
            "mask-repeat": self.mask_repeat,
            "mask-size": self.mask_size ,
            "mask-type": self.mask_type,
            "max-block-size": self.max_block_size,
            "max-height": self.max_height,
            "max-inline-size": self.max_inline_size,
            "max-width": self.max_width,
            "min-block-size": self.min_block_size,
            "min-height": self.min_height,
            "min-inline-size": self.min_inline_size,
            "min-width": self.min_width ,
            "mix-blend-mode": self.mix_blend_mode,
            "object-fit": self.object_fit,
            "object-position": self.object_position ,
            "offset": self.offset,
            "offset-anchor": self.offset_anchor,
            "offset-block": self.offset_block,
            "offset-block-end": self.offset_block_end,
            "offset-block-start": self.offset_block_start,
            "offset-distance": self.offset_distance,
            "offset-inline": self.offset_inline,
            "offset-inline-end": self.offset_inline_end ,
            "offset-inline-start": self.offset_inline_start,
            "offset-path":self.offset_path ,
            "offset-position": self.offset_position,
            "offset-rotate": self.offset_rotate,
            "opacity": self.opacity ,
            "overflow": self.overflow ,
            "order": self.order ,
            "orphans": self.orphans,
            "outline": self.outline,
            "outline-color": self.outline_color,
            "outline-offset": self.outline_offset,
            "outline-style": self.outline_style ,
            "outline-width": self.outline_width ,
            "overflow-anchor": self.overflow_anchor,
            "overflow-block": self.overflow_block,
            "overflow-inline": self.overflow_inline,
            "overflow-wrap": self.overflow_wrap,
            "overflow-x": self.overflow_x,
            "overflow-y": self.overflow_y,
            "overscroll-behavior": self.overscroll_behavior,
            "overscroll-behavior-block": self.overscroll_behavior_block,
            "overscroll-behavior-inline": self.overscroll_behavior_inline,
            "overscroll-behavior-x": self.overscroll_behavior_x,
            "overscroll-behavior-y": self.overscroll_behavior_y,
            "padding": self.padding,
            "padding-block": self.padding_block ,
            "padding-block-end": self.padding_block_end,
            "padding-block-start": self.padding_block_start,
            "padding-bottom": self.padding_bottom,
            "padding-inline": self.padding_inline,
            "padding-inline-end": self.padding_inline_end,
            "padding-inline-start": self.padding_inline_start,
            "padding-left": self.padding_left,
            "padding-right": self.padding_right,
            "padding-top": self.padding_top,
            "page-break-after": self.page_break_after,
            "page-break-before": self.page_break_before,
            "page-break-inside": self.page_break_inside,
            "paint-order": self.paint_order,
            "perspective": self.perspective,
            "perspective-origin": self.perspective_origin,
            "place-content": self.place_content,
            "place-items": self.place_items,
            "place-self": self.place_self,
            "pointer-events": self.pointer_events ,
            "position": self.position,
            "quotes": self.quotes,
            "resize": self.resize,
            "right": self.right,
            "rotate": self.rotate,
            "row-gap": self.row_gap,
            "ruby-align": self.ruby_align,
            "ruby-merge": self.ruby_merge,
            "ruby-position": self.ruby_position,
            "scale": self.scale,
            "scroll-behavior": self.scroll_behavior,
            "scroll-margin": self.scroll_margin,
            "scroll-margin-block": self.scroll_margin_block,
            "scroll-margin-block-end": self.scroll_margin_block_end,
            "scroll-margin-block-start": self.scroll_margin_block_start ,
            "scroll-margin-bottom": self.scroll_margin_bottom ,
            "scroll-margin-inline": self.scroll_margin_inline,
            "scroll-margin-inline-end": self.scroll_margin_inline_end,
            "scroll-margin-inline-start": self.scroll_margin_inline_start,
            "scroll-margin-left": self.scroll_margin_left,
            "scroll-margin-right": self.scroll_margin_right,
            "scroll-margin-top": self.scroll_margin_top,
            "scroll-padding": self.scroll_padding,
            "scroll-padding-block": self.scroll_padding_block ,
            "scroll-padding-block-end": self.scroll_padding_block_end,
            "scroll-padding-block-start": self.scroll_padding_block_start,
            "scroll-padding-bottom": self.scroll_padding_bottom ,
            "scroll-padding-inline": self.scroll_padding_inline,
            "scroll-padding-inline-end": self.scroll_padding_inline_end ,
            "scroll-padding-inline-start": self.scroll_padding_inline_start,
            "scroll-padding-left": self.scroll_padding_left,
            "scroll-padding-right": self.scroll_padding_right ,
            "scroll-padding-top": self.scroll_padding_top ,
            "scroll-snap-align": self.scroll_snap_align,
            "scroll-snap-stop": self.scroll_snap_stop,
            "scroll-snap-type": self.scroll_snap_type,
            "shape-image-threshold": self.shape_image_threshold ,
            "shape-margin": self.shape_margin,
            "shape-outside": self.shape_outside,
            "tab-size": self.tab_size,
            "table-layout": self.table_layout,
            "text-align": self.text_align ,
            "text-align-last": self.text_align_last ,
            "text-combine-upright": self.text_combine_upright,
            "text-decoration": self.text_decoration ,
            "text-decoration-color": self.text_decoration_color ,
            "text-decoration-line": self.text_decoration_line,
            "text-decoration-skip-ink": self.text_decoration_skip_ink ,
            "text-decoration-style": self.text_decoration_style ,
            "text-decoration-thickness": self.text_decoration_thickness,
            "text-emphasis": self.text_emphasis,
            "text-emphasis-color": self.text_emphasis_color,
            "text-emphasis-position": self.text_emphasis_position ,
            "text-emphasis-style": self.text_emphasis_style,
            "text-indent": self.text_indent,
            "text-justify": self.text_justify ,
            "text-orientation": self.text_orientation,
            "text-overflow": self.text_overflow ,
            "text-rendering": self.text_rendering,
            "text-shadow": self.text_shadow,
            "text-size-adjust": self.text_size_adjust,
            "text-transform": self.text_transform,
            "text-underline-offset": self.text_underline_offset ,
            "text-underline-position": self.text_underline_position,
            "top": self.top,
            "touch-action": self.touch_action,
            "transform": self.transform,
            "transform-box": self.transform_box,
            "transform-origin": self.transform_origin ,
            "transform-style": self.transform_style,
            "transition": self.transition,
            "transition-delay": self.transition_delay,
            "transition-duration": self.transition_duration,
            "transition-property": self.transition_property,
            "transition-timing-function": self.transition_timing_function,
            "unicode-bidi": self.unicode_bidi,
            "user-select": self.user_select,
            "vertical-align": self.vertical_align,
            "visibility": self.visibility,
            "white-space": self.white_space ,
            "widows": self.widows,
            "width": self.width,
            "will-change": self.will_change,
            "word-break": self.word_break,
            "word-spacing": self.word_spacing,
            "writing-mode": self.writing_mode,
            "z-index": self.z_index
        }
        return pyload

